### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by rechardchen123** [looput/PSENet#3]
请问如何根据这个训练好的模型的基础上，训练自己的数据集？直接将自己的数据集按照ICDAR的格式准备好就可以了吗？

**Comment by looput** [comment]
参照这个制作tfrecord文件就可以了 [Link](https://github.com/looput/PSENet-Tensorflow/blob/master/dataset/write_tfrecord.py#L13). 训练时可加载多个数据集，你可以多个数据集一起训练，也可以分阶段训练。

**Comment by Tian14267** [comment]
你好，作者的代码是不是缺了一点东西？请问你怎么解决的？tf_extended 和 config。 @rechardchen123

**Comment by rechardchen123** [comment]
> 你好，作者的代码是不是缺了一点东西？请问你怎么解决的？tf_extended 和 config。 @rechardchen123

tf_extended 我是安装了tensorflow 1.5解决的。cofig 这个我没遇到。

**Comment by looput** [comment]
@rechardchen123 更新下了代码，现在无需tf_extented了
