### ISSUE TITLE
IndexError: index 8 is out of bounds for axis 0 with size 8 

### ISSUE THREAD

**Issue by Tian14267** [looput/PSENet#6]
作者你好，我在用CTW数据训练的时候，会报这个错误：" index 8 is out of bounds for axis 0 with size 8 "。
这个错误发生在dataset/preprocess.py的150行左右的“if not label[i]:”处。应该是box的shape[0]和label的个数对不上。请问这个该怎么修改？

**Comment by Tian14267** [comment]
你最新代码的172行 @looput

**Comment by looput** [comment]
https://github.com/looput/PSENet-Tensorflow/blob/689b00e4ab4fe14e1e8788cc31f98f24919a289f/dataset/preprocess.py#L170 这个地方`*4` 改成对应的点数 14

**Comment by looput** [comment]
https://github.com/looput/PSENet-Tensorflow/blob/689b00e4ab4fe14e1e8788cc31f98f24919a289f/dataset/dataloader.py#L15 这个地方的点数也要改下

**Comment by Tian14267** [comment]
可以了。作者非常给力非常6！

**Comment by looput** [comment]
pycharm可以连接服务器远程debug, 可以单步调试程序执行步骤，有助于理解代码和错误排查，你或许可以试下

**Comment by Tian14267** [comment]
我知道的。只是服务器目前无法可视化。试了VNC，结果有bug，不知道作者对VNC是否有了解（笑）
今天把代码的一部分梳理了下，不过还是很多不太理解的。后面会继续学习的。
不知道作者可不可以加一下QQ呢，方便沟通（主要还是有不懂的叨扰你啦，向你看齐）
QQ：969176217

**Comment by looput** [comment]
了解不多, 有问题提issue 就可以了:joy:
